# Generated by Django 5.2.9 on 2026-07-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_updated_at_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('mobile', 'Mobile'), ('design', 'Design'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=50),
        ),
    ]
